import { BaseAgent, type AgentInfo, type AgentInput, type AgentOutput, callLLM, parseJSON, generateImage, generateVideo, uploadToStorage } from './base-agent.ts';

export class VideoMakerAgent extends BaseAgent {
  info: AgentInfo = {
    name: 'video-maker', display_name: 'Video Maker',
    role: 'Video scripts + AI video/thumbnail generation',
    layer: 'creation', color: '#EF4444',
    expertise: ['Video scripting', 'Storyboarding', 'Short-form', 'Veo 2', 'AI video'],
  };

  buildSystemPrompt(vault: any): string {
    const id = vault?.identity || {};
    const t = vault?.semantics?.voice_tone || {};
    const vis = vault?.visual || {};
    const ps = vis.photography_style || {};

    return `You are ORA's Video Maker — ex Brut, Konbini, TikTok-first brands. You create short-form video content that stops thumbs.

BRAND: ${id.name || '?'} | Positioning: ${id.positioning || '?'}
TONE: Formality ${t.formality || 5}/10, Boldness ${t.boldness || 5}/10, Warmth ${t.warmth || 5}/10
VISUAL STYLE: ${ps.description || '?'} | Mood: ${ps.mood_keywords?.join(', ') || '?'}
COLORS: ${vis.colors?.primary || '?'}, ${vis.colors?.secondary || '?'}, ${vis.colors?.accent || '?'}

YOUR JOB: Create a complete video brief that can be:
1. Generated by AI (Veo 2) for quick content
2. Shot by a human team using your storyboard

OUTPUT (JSON only, no markdown):
{
  "title": "<video title>",
  "hook": {
    "time": "0-3s",
    "visual_description": "<exactly what we SEE — be specific for AI generation>",
    "text_overlay": "<on-screen text>",
    "narration": "<voiceover text or null>",
    "audio": "<music/sound direction>"
  },
  "body": [
    {
      "time": "3-8s",
      "visual_description": "<what we see>",
      "text_overlay": "<text or null>",
      "narration": "<voiceover or null>"
    }
  ],
  "cta": {
    "time": "<final 3s>",
    "visual_description": "<what we see>",
    "text_overlay": "<CTA text>",
    "narration": "<voiceover or null>"
  },
  "ai_video_prompt": "<single prompt optimized for Veo 2: describe the full video scene, movement, style, mood — 50-100 words>",
  "ai_thumbnail_prompt": "<prompt for a static thumbnail image>",
  "thumbnail_aspect_ratio": "<9:16 for reels/stories, 16:9 for youtube, 1:1 for feed>",
  "total_duration": "<5s|8s|15s|30s>",
  "music_mood": "<genre and energy>",
  "platform_format": "<9:16|1:1|16:9>",
  "versions": {
    "short": "<how to condense to 5-8s>",
    "medium": "<15s version>",
    "long": "<30s version>"
  }
}

RULES:
- HOOK in first 3 seconds. No logos, no intros. Start with the most compelling visual.
- Visual descriptions must be AI-GENERATION READY: describe camera angle, lighting, subject, action, colors.
- Text overlays use brand fonts/colors.
- Captions mandatory (80% watch without sound).
- The ai_video_prompt should describe ONE continuous scene (Veo 2 generates 5-8s clips).
- Include brand colors in visual descriptions (e.g. "${vis.colors?.primary || 'warm'} tinted lighting").
- The thumbnail must work as a standalone image that makes people click.`;
  }

  async run(input: AgentInput): Promise<AgentOutput> {
    const t = Date.now();
    try {
      // Step 1: Generate the video brief via LLM
      const sys = this.buildSystemPrompt(input.vault);
      const resp = await callLLM(sys, this.buildUserMessage(input));
      const parsed = parseJSON(resp);

      if (!parsed) {
        return { success: true, agent: 'video-maker', content: resp, execution_time_ms: Date.now() - t };
      }

      const media: AgentOutput['media'] = [];
      let thumbnailUrl: string | undefined;
      let videoUrl: string | undefined;

      // Step 2: Generate thumbnail image
      if (parsed.ai_thumbnail_prompt) {
        try {
          const thumbResult = await generateImage(parsed.ai_thumbnail_prompt, {
            aspectRatio: this.mapAspectRatio(parsed.thumbnail_aspect_ratio || parsed.platform_format),
            count: 1,
          });
          if (thumbResult.images.length > 0) {
            const img = thumbResult.images[0];
            const ext = img.mime_type.includes('png') ? 'png' : 'jpg';
            const filename = `video-thumbnails/${Date.now()}-${Math.random().toString(36).substring(7)}.${ext}`;
            try {
              thumbnailUrl = await uploadToStorage(img.base64, img.mime_type, filename);
            } catch { /* storage failed, still have base64 */ }
            media.push({ type: 'image', url: thumbnailUrl, base64: img.base64, mime_type: img.mime_type });
          }
        } catch (thumbErr: any) {
          console.error('Thumbnail generation failed:', thumbErr.message);
        }
      }

      // Step 3: Generate video via Veo 2
      if (parsed.ai_video_prompt) {
        try {
          const videoResult = await generateVideo(parsed.ai_video_prompt, {
            duration: parsed.total_duration === '5s' ? '5s' : '8s',
            aspectRatio: this.mapVideoAspectRatio(parsed.platform_format),
          });

          if (videoResult.status === 'completed' && videoResult.video_url) {
            videoUrl = videoResult.video_url;
            media.push({ type: 'video', url: videoUrl });
          } else if (videoResult.status === 'pending') {
            // Video is still generating — return operation ID
            parsed.video_operation = videoResult.operation_name;
            parsed.video_status = 'generating';
          } else {
            parsed.video_status = 'script_only';
            parsed.video_error = videoResult.error;
          }
        } catch (vidErr: any) {
          console.error('Video generation failed:', vidErr.message);
          parsed.video_status = 'script_only';
          parsed.video_error = vidErr.message;
        }
      }

      // Build explanation
      const parts = [];
      if (thumbnailUrl) parts.push('Thumbnail generated');
      if (videoUrl) parts.push('Video generated');
      if (parsed.video_status === 'generating') parts.push('Video is generating (check back in ~60s)');
      if (parsed.video_status === 'script_only') parts.push('Video script ready (Veo 2 unavailable — use script for manual production or external tools)');
      if (parts.length === 0) parts.push('Video brief generated');

      return {
        success: true,
        agent: 'video-maker',
        content: resp,
        structured_data: {
          ...parsed,
          thumbnail_url: thumbnailUrl,
          video_url: videoUrl,
        },
        image_url: thumbnailUrl,
        video_url: videoUrl,
        media: media.length > 0 ? media : undefined,
        explanation: parts.join('. ') + '.',
        execution_time_ms: Date.now() - t,
      };
    } catch (e: any) {
      return { success: false, agent: 'video-maker', error: e.message, execution_time_ms: Date.now() - t };
    }
  }

  private mapAspectRatio(ratio: string): '1:1' | '3:4' | '4:3' | '9:16' | '16:9' {
    const map: Record<string, any> = {
      '9:16': '9:16', 'vertical': '9:16', 'story': '9:16', 'reel': '9:16',
      '16:9': '16:9', 'landscape': '16:9', 'wide': '16:9', 'youtube': '16:9',
      '1:1': '1:1', 'square': '1:1', 'feed': '1:1',
    };
    return map[ratio?.toLowerCase()] || '9:16';
  }

  private mapVideoAspectRatio(ratio: string): '9:16' | '16:9' | '1:1' {
    if (ratio?.includes('9:16') || ratio?.includes('vertical')) return '9:16';
    if (ratio?.includes('1:1') || ratio?.includes('square')) return '1:1';
    return '16:9';
  }
}
