/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kbvkjafkztbsewtaijuh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtidmtqYWZrenRic2V3dGFpanVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5MTk2ODksImV4cCI6MjA4NzQ5NTY4OX0.ty1aiV63wnINUkViZNzlNAHFzL0mdvSRjzRDd-lB-sk"